### ISSUE TITLE
local variable 'sentencepiece_model_pb2' referenced before assignment

### ISSUE THREAD

**Issue by wangjx22** [blender-nlp/MolT5#11]
**I am trying to run a script as follows:** 
from transformers import T5Tokenizer, T5ForConditionalGeneration, AutoTokenizer
model = T5ForConditionalGeneration.from_pretrained('/remote-home/jinxianwang/code/MolT5-main/molt5-large-smiles2caption')
tokenizer = T5Tokenizer.from_pretrained("/remote-home/jinxianwang/code/MolT5-main/molt5-large-smiles2caption", model_max_length=512)

**But have show  an UnboundLocalError as follows:**
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=True`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
False
Traceback (most recent call last):
  File "/remote-home/jinxianwang/code/MolT5-main/test.py", line 4, in <module>
    tokenizer = T5Tokenizer.from_pretrained("/remote-home/jinxianwang/code/MolT5-main/molt5-large-smiles2caption", model_max_length=512)
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5.py", line 194, in __init__
    self.sp_model = self.get_spm_processor()
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5.py", line 200, in get_spm_processor
    model_pb2 = import_protobuf() 
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 44, in import_protobuf
    return sentencepiece_model_pb2
UnboundLocalError: local variable 'sentencepiece_model_pb2' referenced before assignment

I download the model and dataset from the [Hugging Face](https://huggingface.co/)  as the input of code.
Did you have any idea for these issues?

**Comment by cnedwards** [comment]
Hello,

I don't specifically know what is causing the issue, but I would guess it is a package version issue when combined with loading offline files. It looks like it might be related to https://github.com/huggingface/transformers/pull/24565 . 

I can create an AutoTokenizer without installing sentencepiece on my side. If I use T5Tokenizer, it requires sentencepiece to be installed. 

Code I ran:
```
from transformers import T5Tokenizer, T5ForConditionalGeneration, AutoTokenizer
model = T5ForConditionalGeneration.from_pretrained('laituan245/molt5-small-smiles2caption')
tokenizer = T5Tokenizer.from_pretrained('laituan245/molt5-small-smiles2caption')

```
with transformers version 4.37.2.
