### ISSUE TITLE
Pre trained embedding

### ISSUE THREAD

**Issue by ethancohen123** [blender-nlp/MolT5#3]
Hi,
Is it possible to access the trained molecular embedding only for downstream task ? 
Thanks

**Comment by laituan245** [comment]
Hi.

I am not sure if I understand your question exactly. Given a SMILES string, you want to get its embeddings?

Maybe the code snippet below will be helpful (here, I am using `laituan245/molt5-small-smiles2caption `).
```
from transformers import T5Tokenizer, T5EncoderModel

tokenizer = T5Tokenizer.from_pretrained("laituan245/molt5-small-smiles2caption")
model = T5EncoderModel.from_pretrained("laituan245/molt5-small-smiles2caption")
input_ids = tokenizer("C1=CC2=C(C(=C1)[O-])NC(=CC2=O)C(=O)O", return_tensors="pt").input_ids
outputs = model(input_ids=input_ids)
last_hidden_states = outputs.last_hidden_state

```

**Comment by ethancohen123** [comment]
Yes perfect that is what I wanted. 
One other thing concerning the tokenizer ( seems to be a more general question regarding tokenization ) : During dataloading process for a random task, should I tokenize everything at the beginning (let's say I have a dataframe of smiles string)  or should I tokenize each smiles one by one in the get_item_ function ?
Thanks a lot !

**Comment by laituan245** [comment]
So suppose you have a list of SMILES strings, you can just use the default function of the tokenizer to tokenize them. It will automatically handle padding and stuff. It is quite convenient. For example:

```
from transformers import T5Tokenizer, T5EncoderModel

tokenizer = T5Tokenizer.from_pretrained("laituan245/molt5-small-smiles2caption")
model = T5EncoderModel.from_pretrained("laituan245/molt5-small-smiles2caption")
list_of_smiles = ["C1=CC2=C(C(=C1)[O-])NC(=CC2=O)C(=O)O", "CC(=O)OC1=CC=CC=C1C(=O)O"]
input_ids = tokenizer(list_of_smiles, return_tensors="pt", padding='longest').input_ids
outputs = model(input_ids=input_ids)
last_hidden_states = outputs.last_hidden_state
```

Some of the options for padding is like `padding`, `longest` ... 

I hope that answers your question.
In general, our models are like seq2seq models in HuggingFace. Please refer to their documentation as well.

**Comment by ethancohen123** [comment]
Thanks a lot !
