### ISSUE TITLE
Download cid_to_smiles.pkl

### ISSUE THREAD

**Issue by ddz16** [blender-nlp/MolT5#4]
Great Job! I can't download the cid_to_smiles.pkl file due to the 1GB free limit on Github LFS. Could you provide other download links, such as Google Drive? Thanks a lot!

**Comment by laituan245** [comment]
Thank you for your interest.

Please download the file here: https://uofi.box.com/s/3mnkv804gtv83mmaqpyw5tomb5aac08p
Let me know if you could not access it.

Thanks.

**Comment by ddz16** [comment]
Thanks a lot! Now I can download this file successfully!

**Comment by ddz16** [comment]
Excuse me, I want to run text_text2mol_metric.py. It also needs **test_outputfinal_weights.320.pt**, which is still provided by Github LFS. Could you provide other links to download **test_outputfinal_weights.320.pt**?

**Comment by laituan245** [comment]
@cnedwards Could you provide the download link?

**Comment by cnedwards** [comment]
Please use this https://uofi.box.com/s/es16alnhzfy1hpagf55fu48k49f8n29x . 

I'll look into removing the reliance on GIT LFS soon.

**Comment by cnedwards** [comment]
Hi all, for anyone reading this in the future, please use https://uofi.box.com/v/MolT5-cid-to-smiles for cid_to_smiles.pkl instead.

Thanks!
