### ISSUE TITLE
Questions About Using Text2Mol Evaluation Metric

### ISSUE THREAD

**Issue by Frankie123421** [blender-nlp/MolT5#5]
Hi, thanks for sharing the code.

I am trying to use your proposed Text2Mol Evaluation Metric. However, I encountered the following errors when I run the code. 

Traceback (most recent call last):
  File "text_text2mol_metric.py", line 60, in <module>
    cids_to_smiles = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'

And I try to replace the 'cid_to_smiles.pkl' with the downloaded 3GB version, then another issue arises: Chem.MolFromSmiles(cids_to_smiles[cid]) generates Nonetype.

I don't know if the problem comes from the version of Python or other packages. Could you please help me fix it, thank you in advance.

**Comment by cnedwards** [comment]
Hi Frankie,

I'm not sure what's causing this. Can you provide more details on your python installation, environment, and OS? Also, can you try running the following?

```import pickle
with open('cids_to_smiles.pkl', 'rb') as f:
    tmp = pickle.load(f)
print(type(tmp))
print(tmp[425291])
```

Thanks!

**Comment by Frankie123421** [comment]
Hi, thanks for your kind and prompt reply.

My OS is linux, and the version of python is 3.7.0, I know that your installed python may be >=3.9.0 because "action=argparse.BooleanOptionalAction" only works in that case, and I just simply modify it to fit my python. The environment (versions of installed packages) is as follows (some may seems to be useless).

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
boost                     1.72.0           py37h48f8a5e_1    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
bottleneck                1.3.4            py37hda87dfa_1    conda-forge
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2022.6.15            ha878542_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2022.6.15        py37h89c1867_0    conda-forge
cffi                      1.15.0           py37h7f8727e_0  
charset-normalizer        2.1.0                    pypi_0    pypi
cryptography              37.0.1           py37h9ce1e76_0  
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   pypi_0    pypi
easydict                  1.9                      pypi_0    pypi
expat                     2.4.8                h27087fc_0    conda-forge
fcd-torch                 1.0.7                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.8.0                    pypi_0    pypi
fontconfig                2.14.0               h8e229c2_0    conda-forge
freetype                  2.11.0               h70c0345_0  
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h7b6447c_0  
glib                      2.66.3               h58526e2_0    conda-forge
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
huggingface-hub           0.9.0                    pypi_0    pypi
icu                       64.2                 he1b5a44_1    conda-forge
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.0.3              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9e                   h7f8727e_0  
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
libedit                   3.1.20210910         h7f8727e_0  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h2818925_1  
libunistring              0.9.10               h27cfd23_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.13              h7f98852_1004    conda-forge
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.1.1            py37h7f8727e_0  
matplotlib                3.4.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
molsets                   0.3.1                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3              pyhd3eb1b0_0  
numexpr                   2.7.3            py37he8f5f7f_1    conda-forge
numpy                     1.20.3                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openssl                   1.0.2u               h516909a_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.1.5                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    9.2.0            py37hace64e9_1  
pip                       22.1.2           py37h06a4308_0  
pixman                    0.38.0            h516909a_1003    conda-forge
pomegranate               0.12.0                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pubchempy                 1.0.4                      py_3    mcs07
pycairo                   1.21.0           py37h0afab05_1    conda-forge
pycparser                 2.21               pyhd3eb1b0_0  
pyemd                     0.5.1                    pypi_0    pypi
pyg                       2.0.4           py37_torch_1.10.0_cu102    pyg
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    py37_1  
python                    3.7.0                h6e4f718_3  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd3eb1b0_0  
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.10.1          py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-cluster           1.6.0           py37_torch_1.10.0_cu102    pyg
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.0.9           py37_torch_1.10.0_cu102    pyg
pytorch-sparse            0.6.13          py37_torch_1.10.0_cu102    pyg
pytorch-spline-conv       1.2.1           py37_torch_1.10.0_cu102    pyg
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
rdkit                     2020.09.1        py37h53b44e5_0    conda-forge
readline                  7.0                  h7b6447c_5  
regex                     2022.8.17                pypi_0    pypi
requests                  2.28.1           py37h06a4308_0  
scikit-learn              1.0.2            py37h51133e4_1  
scipy                     1.7.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                61.2.0           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.12.1                   pypi_0    pypi
torchaudio                0.10.1               py37_cu102    pytorch
torchvision               0.11.2               py37_cu102    pytorch
tqdm                      4.64.0           py37h06a4308_0  
transformers              4.21.1                   pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0  
urllib3                   1.26.10                  pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7f8727e_1  
yacs                      0.1.6              pyhd3eb1b0_1  
yaml                      0.2.5                h7b6447c_0  
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2  
zstd                      1.5.2                ha4553b6_0

And I tried running the code (I think 'cids_to_smiles.pkl' is the downloaded 3GB one?), the result is

```
<class 'dict'>
C1=CC=C2C=C(C=CC2=C1)CN(CCCl)CCCl
```

I also tried to filter the Nonetype by

```
for cid in cids_to_smiles:
    if cids_to_smiles[cid] == '*': continue
    m = Chem.MolFromSmiles(cids_to_smiles[cid])
    if m is None:
        print(cids_to_smiles[cid])
        continue
    smi = Chem.MolToSmiles(m)
    cids_to_smiles[cid] = smi
```

It's overall very slow and I don't know if it's normal. I show some of the filtered smiles as below.

```
O=Cl(=O)(=O)F
F[Si-2](F)(F)(F)(F)F.[Zn+2]
F[Si-2](F)(F)(F)(F)F
F[Si-2](F)(F)(F)(F)F.[Na+].[Na+]
[NH4+].[NH4+].F[Si-2](F)(F)(F)(F)F
F[Si-2](F)(F)(F)(F)F.[Ba+2]
F[Ge-2](F)(F)(F)(F)F.[Mg+2]
```

If you need more information about the issue, please ask me for free. Thanks.

**Comment by cnedwards** [comment]
Hi Frankie,

Can you try with this file? 
https://uofi.box.com/v/MolT5-cid-to-smiles

Thanks!

**Comment by Frankie123421** [comment]
Hi Carl,

Thanks for your reply. It works with your provided file!! (Could you tell me the reason?) And I also encountered the same issue (i.e.,  _pickle.UnpicklingError: invalid load key, 'v') when loading the model weights, but it's solved by replacing with the downloaded one. The remaining question is that when I ran the command "./mol_text2mol_metric.sh caption2smiles_example.txt", it raised an error "./m2v.sh: line 4: mol2vec: command not found". Could you please help me fix it? Thanks!!

Best, 
Frankie

**Comment by cnedwards** [comment]
Hi Frankie,

Sorry for the delayed response. The reason is because the file which was linked was a different file from earlier in development. The other Github user didn't have an issue for whatever reason. I uploaded the correct file (which is the one in this repo).

Regarding "mol2vec: command not found", you need to install mol2vec. There should be more information here: https://github.com/samoturk/mol2vec . 

Thanks!

**Comment by Frankie123421** [comment]
Thanks for your response and answer. I've installed mol2vec and rerun the command, but unfortunately encountered another loading error: 

Traceback (most recent call last):
  File "/home/anaconda3/envs/gdss/bin/mol2vec", line 8, in <module>
    sys.exit(run())
  File "/home/anaconda3/envs/gdss/lib/python3.7/site-packages/mol2vec/app/mol2vec.py", line 165, in run
    args.func(args)
  File "/home/anaconda3/envs/gdss/lib/python3.7/site-packages/mol2vec/app/mol2vec.py", line 25, in do_featurize
    features.featurize(args.in_file, args.out_file, args.model, args.radius, args.uncommon)
  File "/home/anaconda3/envs/gdss/lib/python3.7/site-packages/mol2vec/features.py", line 462, in featurize
    word2vec_model = word2vec.Word2Vec.load(model_path)
  File "/home/anaconda3/envs/gdss/lib/python3.7/site-packages/gensim/models/word2vec.py", line 1939, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/anaconda3/envs/gdss/lib/python3.7/site-packages/gensim/utils.py", line 486, in load
    obj = unpickle(fname)
  File "/home/anaconda3/envs/gdss/lib/python3.7/site-packages/gensim/utils.py", line 1461, in unpickle
    return _pickle.load(f, encoding='latin1')  # needed because loading from S3 doesn't support readline()
_pickle.UnpicklingError: invalid load key, 'v'.

It seems that something goes wrong when loading in mol2vec. I wonder if you know how to fix it. Feel sorry for bothering you so many times )-:

**Comment by cnedwards** [comment]
Hi Frankie,

I recall that an update to gensim early last year broke mol2vec (<s>I believe it was 3.0</s>).

That might fix things.

edit:
It was 4.0. See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4 . Hopefully this might fix your issue.

**Comment by Frankie123421** [comment]
Thanks for your reply. My installed version of gensim is 4.2.0, I tried 3.0 but it still failed. Could you please share the version you installed? Thanks.

**Comment by cnedwards** [comment]
It looks like I used gensim 3.8.3. Can you try creating a new conda environment by following the installation instructions here? https://github.com/blender-nlp/MolT5/tree/main/evaluation

**Comment by Frankie123421** [comment]
OH, thanks. I just ignored that before, thanks for it and your kind answers these days!
