### ISSUE TITLE
Environment setting and re-train with other drug description

### ISSUE THREAD

**Issue by lichman0405** [blender-nlp/MolT5#6]
Hi Sir or Madam,
I am very stunning by your work, and I would like to re-train the pre-train model with other description of drugs.
However, I cannot find how to install. Could you please update the repo so that I may do my set?

Gracias!

**Comment by laituan245** [comment]
Hi Shibo,

Please see the description of how to do the pre-training here: https://github.com/blender-nlp/MolT5#pretraining-molt5-based-models

The description of how to do the fine-tuning here: https://github.com/blender-nlp/MolT5#finetuning-molt5-based-models

Please let me know if you have any specific question about the pre-training/fine-tuning procedure.

We have also published our models as HuggingFace-based models. You can finetune our pretrained models just like finetuning any HuggingFace models: https://github.com/blender-nlp/MolT5#huggingface-model-checkpoints

Here is a relevant tutorial: https://huggingface.co/docs/transformers/model_doc/t5
